const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILED = 'LOGIN_FAILED'
const LOGIN_OUT = 'LOGIN_OUT'

const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
const REGISTER_FAILED = 'REGISTER_FAILED'

const REQUEST_BEGIN = 'REQUEST_BEGIN'
const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
const REQUEST_FAILED = 'REQUEST_FAILED'


export {
  LOGIN_FAILED,
  LOGIN_SUCCESS,
  REGISTER_FAILED,
  REGISTER_SUCCESS,
  REQUEST_BEGIN,
  REQUEST_FAILED,
  REQUEST_SUCCESS,
  LOGIN_OUT
}
